---
services:

  mongo-atlas-local:
    image: mongodb/mongodb-atlas-local:7.0.14 # Use a specific version matching your production Atlas version
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - mongodb_mongot:/data/mongot # Persist the search index data

  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=inventory


  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true

  # NOTE: As of 2026-01-15 pinecone-local still only supports API version 2025-01 which requires SDK 6.*
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment:
      PORT: 5080
      PINECONE_HOST: localhost
    ports:
      - "5080-5090:5080-5090"
    platform: linux/amd64

volumes:
  mongodb_data:
  mongodb_config:
  mongodb_mongot:
